version: '3'
services:
  assistant:
    restart: unless-stopped
    container_name: assistant
    build:
      context: ./assistant
    command: sh -c "cargo watch -x run"
    depends_on:
      - mqtt
    networks:
      - mqtt

  mqtt:
    restart: unless-stopped
    container_name: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mqtt

networks:
  mqtt:
    name: mqtt
    driver: bridge
